### ISSUE TITLE
doh-client has a serious memory leak problem under high concurrency

### ISSUE THREAD

**Issue by yingziwu** [m13253/dns-over-https#72]
# problem description

## Background

- BIND 9.16.1 (Stable Release)
- dns-over-https (59f79fb666208bb307374d33111925f183388855)
- Linux localhost 5.5.11-arch1-1 SMP PREEMPT Sun, x86_64 GNU/Linux

Architecture:

- BIND forwards some DNS requests to doh-client.
- BIND enables ``dnssec-validation``.
- Add NTA (negative trust anchor) for some domain names.

## Phenomenon

The doh-client has high memory usage. When the memory usage reaches a certain level (greater than 5G), the program exits abnormally.

Screen capture at 3.7G memory
![3 7G](https://user-images.githubusercontent.com/22741471/77634404-d8ffc700-6f8b-11ea-908f-a1c948c85e26.png)

doh-client.service keeps restarting
![systemd-unit](https://user-images.githubusercontent.com/22741471/77634435-eae16a00-6f8b-11ea-9b5b-1bba57efb3e2.png)

Above, at the 6th time, 39208 process memory layout
```
# pmap 39208
39208:   /usr/bin/doh-client -conf /etc/dns-over-https/doh-client.conf
000000c000000000 1011712K rw---   [ anon ]
000000c03dc00000   2048K rw---   [ anon ]
000000c03de00000  20480K rw---   [ anon ]
000000c03f200000   2048K rw---   [ anon ]
000000c03f400000   4096K rw---   [ anon ]
000000c03f800000  18432K rw---   [ anon ]
000000c040a00000  12288K rw---   [ anon ]
000000c041600000   2048K rw---   [ anon ]
000000c041800000  81920K rw---   [ anon ]
000000c046800000   2048K rw---   [ anon ]
000000c046a00000   4096K rw---   [ anon ]
000000c046e00000   2048K rw---   [ anon ]
000000c047000000   6144K rw---   [ anon ]
000000c047600000   2048K rw---   [ anon ]
000000c047800000   4096K rw---   [ anon ]
000000c047c00000   2048K rw---   [ anon ]
000000c047e00000  12288K rw---   [ anon ]
000000c048a00000 2082816K rw---   [ anon ]
000000c0c7c00000   2048K rw---   [ anon ]
000000c0c7e00000 796672K rw---   [ anon ]
000000c0f8800000   2048K rw---   [ anon ]
000000c0f8a00000  55296K rw---   [ anon ]
000055ee746a3000   1652K r---- doh-client
000055ee74840000   3260K r-x-- doh-client
000055ee74b6f000    512K r---- doh-client
000055ee74bef000   2852K r---- doh-client
000055ee74eb8000    320K rw--- doh-client
000055ee74f08000    192K rw---   [ anon ]
000055ee757cf000    132K rw---   [ anon ]
00007f7e3f521000  68484K rw---   [ anon ]
00007f7e4380d000  35188K rw---   [ anon ]
00007f7e45a6c000  30316K rw---   [ anon ]
00007f7e4780e000   8136K rw---   [ anon ]
00007f7e48000000    132K rw---   [ anon ]
00007f7e48021000  65404K -----   [ anon ]
00007f7e4c000000    132K rw---   [ anon ]
00007f7e4c021000  65404K -----   [ anon ]
00007f7e50000000    132K rw---   [ anon ]
00007f7e50021000  65404K -----   [ anon ]
00007f7e54000000    132K rw---   [ anon ]
00007f7e54021000  65404K -----   [ anon ]
00007f7e58000000    132K rw---   [ anon ]
00007f7e58021000  65404K -----   [ anon ]
00007f7e5c000000    132K rw---   [ anon ]
00007f7e5c021000  65404K -----   [ anon ]
00007f7e60008000   9932K rw---   [ anon ]
00007f7e609c5000   9228K rw---   [ anon ]
00007f7e612c9000   5320K rw---   [ anon ]
00007f7e617fb000      4K -----   [ anon ]
00007f7e617fc000   8192K rw---   [ anon ]
00007f7e61ffc000      4K -----   [ anon ]
00007f7e61ffd000   8192K rw---   [ anon ]
00007f7e627fd000      4K -----   [ anon ]
00007f7e627fe000   8192K rw---   [ anon ]
00007f7e62ffe000      4K -----   [ anon ]
00007f7e62fff000   8192K rw---   [ anon ]
00007f7e637ff000      4K -----   [ anon ]
00007f7e63800000   8192K rw---   [ anon ]
00007f7e64000000    132K rw---   [ anon ]
00007f7e64021000  65404K -----   [ anon ]
00007f7e68000000    132K rw---   [ anon ]
00007f7e68021000  65404K -----   [ anon ]
00007f7e6c000000    132K rw---   [ anon ]
00007f7e6c021000  65404K -----   [ anon ]
00007f7e70000000    132K rw---   [ anon ]
00007f7e70021000  65404K -----   [ anon ]
00007f7e74000000    132K rw---   [ anon ]
00007f7e74021000  65404K -----   [ anon ]
00007f7e78000000    132K rw---   [ anon ]
00007f7e78021000  65404K -----   [ anon ]
00007f7e7c000000    132K rw---   [ anon ]
00007f7e7c021000  65404K -----   [ anon ]
00007f7e8000d000   1728K rw---   [ anon ]
00007f7e801c3000   3332K rw---   [ anon ]
00007f7e80508000   3012K rw---   [ anon ]
00007f7e807f9000      4K -----   [ anon ]
00007f7e807fa000   8192K rw---   [ anon ]
00007f7e80ffa000      4K -----   [ anon ]
00007f7e80ffb000   8192K rw---   [ anon ]
00007f7e817fb000      4K -----   [ anon ]
00007f7e817fc000   8192K rw---   [ anon ]
00007f7e81ffc000      4K -----   [ anon ]
00007f7e81ffd000   8192K rw---   [ anon ]
00007f7e827fd000      4K -----   [ anon ]
00007f7e827fe000   8192K rw---   [ anon ]
00007f7e82ffe000      4K -----   [ anon ]
00007f7e82fff000   8192K rw---   [ anon ]
00007f7e837ff000      4K -----   [ anon ]
00007f7e83800000   8192K rw---   [ anon ]
00007f7e84000000    132K rw---   [ anon ]
00007f7e84021000  65404K -----   [ anon ]
00007f7e88000000    132K rw---   [ anon ]
00007f7e88021000  65404K -----   [ anon ]
00007f7e8c000000    132K rw---   [ anon ]
00007f7e8c021000  65404K -----   [ anon ]
00007f7e90000000    132K rw---   [ anon ]
00007f7e90021000  65404K -----   [ anon ]
00007f7e94000000    132K rw---   [ anon ]
00007f7e94021000  65404K -----   [ anon ]
00007f7e98000000    132K rw---   [ anon ]
00007f7e98021000  65404K -----   [ anon ]
00007f7e9c000000    132K rw---   [ anon ]
00007f7e9c021000  65404K -----   [ anon ]
00007f7ea0001000    384K rw---   [ anon ]
00007f7ea0069000   5124K rw---   [ anon ]
00007f7ea056a000     16K r---- libresolv-2.31.so
00007f7ea056e000     52K r-x-- libresolv-2.31.so
00007f7ea057b000     12K r---- libresolv-2.31.so
00007f7ea057e000      4K ----- libresolv-2.31.so
00007f7ea057f000      4K r---- libresolv-2.31.so
00007f7ea0580000      4K rw--- libresolv-2.31.so
00007f7ea0581000      8K rw---   [ anon ]
00007f7ea0583000     28K r---- libnss_resolve.so.2
00007f7ea058a000    200K r-x-- libnss_resolve.so.2
00007f7ea05bc000     68K r---- libnss_resolve.so.2
00007f7ea05cd000      4K ----- libnss_resolve.so.2
00007f7ea05ce000     12K r---- libnss_resolve.so.2
00007f7ea05d1000      4K rw--- libnss_resolve.so.2
00007f7ea05d2000      4K rw---   [ anon ]
00007f7ea05d3000     12K r---- libnss_myhostname.so.2
00007f7ea05d6000     40K r-x-- libnss_myhostname.so.2
00007f7ea05e0000     32K r---- libnss_myhostname.so.2
00007f7ea05e8000     12K r---- libnss_myhostname.so.2
00007f7ea05eb000      4K rw--- libnss_myhostname.so.2
00007f7ea05ec000     28K r---- libnss_mymachines.so.2
00007f7ea05f3000    204K r-x-- libnss_mymachines.so.2
00007f7ea0626000     68K r---- libnss_mymachines.so.2
00007f7ea0637000      4K ----- libnss_mymachines.so.2
00007f7ea0638000     12K r---- libnss_mymachines.so.2
00007f7ea063b000      4K rw--- libnss_mymachines.so.2
00007f7ea063c000      4K rw---   [ anon ]
00007f7ea063d000     12K r---- libnss_files-2.31.so
00007f7ea0640000     28K r-x-- libnss_files-2.31.so
00007f7ea0647000      8K r---- libnss_files-2.31.so
00007f7ea0649000      4K r---- libnss_files-2.31.so
00007f7ea064a000      4K rw--- libnss_files-2.31.so
00007f7ea064b000    280K rw---   [ anon ]
00007f7ea069a000    256K rw---   [ anon ]
00007f7ea06da000      4K -----   [ anon ]
00007f7ea06db000   8192K rw---   [ anon ]
00007f7ea0edb000      4K -----   [ anon ]
00007f7ea0edc000   8448K rw---   [ anon ]
00007f7ea171c000      4K -----   [ anon ]
00007f7ea171d000   8448K rw---   [ anon ]
00007f7ea1f5d000      4K -----   [ anon ]
00007f7ea1f5e000   8192K rw---   [ anon ]
00007f7ea275e000      4K -----   [ anon ]
00007f7ea275f000   8448K rw---   [ anon ]
00007f7ea2f9f000      4K -----   [ anon ]
00007f7ea2fa0000   8192K rw---   [ anon ]
00007f7ea37a0000      4K -----   [ anon ]
00007f7ea37a1000   8192K rw---   [ anon ]
00007f7ea3fa1000      4K -----   [ anon ]
00007f7ea3fa2000  44228K rw---   [ anon ]
00007f7ea6ad3000 263680K -----   [ anon ]
00007f7eb6c53000      8K rw---   [ anon ]
00007f7eb6c55000 293560K -----   [ anon ]
00007f7ec8b03000      4K rw---   [ anon ]
00007f7ec8b04000  36692K -----   [ anon ]
00007f7ecaed9000      4K rw---   [ anon ]
00007f7ecaeda000   4580K -----   [ anon ]
00007f7ecb353000      4K rw---   [ anon ]
00007f7ecb354000    508K -----   [ anon ]
00007f7ecb3d3000    140K rw---   [ anon ]
00007f7ecb3f6000    148K r---- libc-2.31.so
00007f7ecb41b000   1328K r-x-- libc-2.31.so
00007f7ecb567000    300K r---- libc-2.31.so
00007f7ecb5b2000     12K r---- libc-2.31.so
00007f7ecb5b5000     12K rw--- libc-2.31.so
00007f7ecb5b8000     16K rw---   [ anon ]
00007f7ecb5bc000     28K r---- libpthread-2.31.so
00007f7ecb5c3000     64K r-x-- libpthread-2.31.so
00007f7ecb5d3000     20K r---- libpthread-2.31.so
00007f7ecb5d8000      4K r---- libpthread-2.31.so
00007f7ecb5d9000      4K rw--- libpthread-2.31.so
00007f7ecb5da000     24K rw---   [ anon ]
00007f7ecb5e0000      8K r---- libnss_dns-2.31.so
00007f7ecb5e2000     16K r-x-- libnss_dns-2.31.so
00007f7ecb5e6000      4K r---- libnss_dns-2.31.so
00007f7ecb5e7000      4K r---- libnss_dns-2.31.so
00007f7ecb5e8000      4K rw--- libnss_dns-2.31.so
00007f7ecb5e9000    256K rw---   [ anon ]
00007f7ecb629000      8K r---- ld-2.31.so
00007f7ecb62b000    128K r-x-- ld-2.31.so
00007f7ecb64b000     32K r---- ld-2.31.so
00007f7ecb654000      4K r---- ld-2.31.so
00007f7ecb655000      4K rw--- ld-2.31.so
00007f7ecb656000      4K rw---   [ anon ]
00007ffe1e804000    132K rw---   [ stack ]
00007ffe1e93b000     12K r----   [ anon ]
00007ffe1e93e000      4K r-x--   [ anon ]
ffffffffff600000      4K --x--   [ anon ]
 total          6432516K
```

The log of doh-client exits abnormally
```
……
Mar 26 03:29:36 localhost doh-client[78140]: 2020/03/26 03:29:35 Get "https://jcdns.fun/dns-query?ct=application/dns-message&dns=AAABEAABAAAAAAABCWlkZXJlY2VzcwJjZgAALwABAAApAgAAAIAAABwACgAYRKLfWfFbztgBAAAAXnurZTKZzQnFoEZ1": write tcp 192.168.0.102:50464->178.62.214.105:443: write: connection timed out
Mar 26 03:29:36 localhost doh-client[78140]: 2020/03/26 03:29:35 Get "https://jcdns.fun/dns-query?ct=application/dns-message&dns=AAABEAABAAAAAAABCmZhbmdlcWlhbmcDY29tAAAvAAEAACkEgAAAgAAAHAAKABiYEf2UnpS0m6dBjxVee6uC7xfPqeRbI00": write tcp 192.168.0.102:50464->178.62.214.105:443: write: connection timed out
Mar 26 03:29:36 localhost doh-client[78140]: 2020/03/26 03:29:35 Get "https://jcdns.fun/dns-query?ct=application/dns-message&dns=AAABEAABAAAAAAABEnRpYmV0YW5jb21tdW5pdHl1awNuZXQAAC8AAQAAKQIAAACAAAAcAAoAGESi31nxW87YAQAAAF57q2Uymc0JxaBGdQ": write tcp 192.168.0.102:50464->178.62.214.105:443: write: connection timed out
Mar 26 03:29:36 localhost doh-client[78140]: panic: runtime error: racy use of timers
Mar 26 03:29:36 localhost doh-client[78140]: goroutine 1265166 [running]:
Mar 26 03:29:36 localhost doh-client[78140]: time.stopTimer(0xc044a6d278, 0x0)
Mar 26 03:29:36 localhost doh-client[78140]:         /usr/lib/go/src/runtime/time.go:224 +0x2d
Mar 26 03:29:36 localhost doh-client[78140]: time.(*Timer).Stop(...)
Mar 26 03:29:36 localhost doh-client[78140]:         /usr/lib/go/src/time/sleep.go:78
Mar 26 03:29:36 localhost doh-client[78140]: golang.org/x/net/http2.(*ClientConn).roundTrip(0xc01e378480, 0xc0025d7d00, 0x0, 0x0, 0x0, 0x0)
Mar 26 03:29:36 localhost doh-client[78140]:         /build/dns-over-https/src/go/pkg/mod/golang.org/x/net@v0.0.0-20191027093000-83d349e8ac1a/http2/transport.go:968 +0xa1
Mar 26 03:29:36 localhost doh-client[78140]: golang.org/x/net/http2.(*Transport).RoundTripOpt(0xc000022780, 0xc0025d7d00, 0x56281cf7d400, 0xc00017d2c0, 0xc0025dc000, 0x5)
Mar 26 03:29:36 localhost doh-client[78140]:         /build/dns-over-https/src/go/pkg/mod/golang.org/x/net@v0.0.0-20191027093000-83d349e8ac1a/http2/transport.go:447 +0x171
Mar 26 03:29:36 localhost doh-client[78140]: golang.org/x/net/http2.(*Transport).RoundTrip(...)
Mar 26 03:29:36 localhost doh-client[78140]:         /build/dns-over-https/src/go/pkg/mod/golang.org/x/net@v0.0.0-20191027093000-83d349e8ac1a/http2/transport.go:408
Mar 26 03:29:36 localhost doh-client[78140]: golang.org/x/net/http2.noDialH2RoundTripper.RoundTrip(0xc000022780, 0xc0025d7d00, 0x56281cff3100, 0xc000022780, 0x0)
Mar 26 03:29:36 localhost doh-client[78140]:         /build/dns-over-https/src/go/pkg/mod/golang.org/x/net@v0.0.0-20191027093000-83d349e8ac1a/http2/transport.go:2589 +0x40
Mar 26 03:29:36 localhost doh-client[78140]: net/http.(*Transport).roundTrip(0xc0001308c0, 0xc0025d7d00, 0xc020c99960, 0xc009858688, 0x56281cb95a8a)
Mar 26 03:29:36 localhost doh-client[78140]:         /usr/lib/go/src/net/http/transport.go:515 +0xd96
Mar 26 03:29:36 localhost doh-client[78140]: net/http.(*Transport).RoundTrip(0xc0001308c0, 0xc0025d7d00, 0xc0001308c0, 0x0, 0x0)
Mar 26 03:29:36 localhost doh-client[78140]:         /usr/lib/go/src/net/http/roundtrip.go:17 +0x37
Mar 26 03:29:36 localhost doh-client[78140]: net/http.send(0xc0025d7d00, 0x56281cff2860, 0xc0001308c0, 0x0, 0x0, 0x0, 0xc00a9bf9f8, 0x203000, 0x1, 0x0)
Mar 26 03:29:36 localhost doh-client[78140]:         /usr/lib/go/src/net/http/client.go:252 +0x440
Mar 26 03:29:36 localhost doh-client[78140]: net/http.(*Client).send(0xc00017d320, 0xc0025d7d00, 0x0, 0x0, 0x0, 0xc00a9bf9f8, 0x0, 0x1, 0xc0025d7c00)
Mar 26 03:29:36 localhost doh-client[78140]:         /usr/lib/go/src/net/http/client.go:176 +0xfc
Mar 26 03:29:36 localhost doh-client[78140]: net/http.(*Client).do(0xc00017d320, 0xc0025d7d00, 0x0, 0x0, 0x0)
Mar 26 03:29:36 localhost doh-client[78140]:         /usr/lib/go/src/net/http/client.go:699 +0x44c
Mar 26 03:29:36 localhost doh-client[78140]: net/http.(*Client).Do(...)
Mar 26 03:29:36 localhost doh-client[78140]:         /usr/lib/go/src/net/http/client.go:567
Mar 26 03:29:36 localhost doh-client[78140]: main.(*Client).generateRequestIETF(0xc00007bee0, 0x56281cff8940, 0xc013532cc0, 0x56281cffc460, 0xc013532c60, 0xc01460d7a0, 0x0, 0xc00002b300, 0xe)
Mar 26 03:29:36 localhost doh-client[78140]:         doh-client/ietf.go:138 +0x98a
Mar 26 03:29:36 localhost doh-client[78140]: main.(*Client).handlerFunc(0xc00007bee0, 0x56281cffc460, 0xc013532c60, 0xc01460d7a0, 0xc014c23000)
Mar 26 03:29:36 localhost doh-client[78140]:         doh-client/client.go:378 +0x40d
Mar 26 03:29:36 localhost doh-client[78140]: main.(*Client).udpHandlerFunc(...)
Mar 26 03:29:36 localhost doh-client[78140]:         doh-client/client.go:443
Mar 26 03:29:36 localhost doh-client[78140]: github.com/miekg/dns.HandlerFunc.ServeDNS(0xc0001821b0, 0x56281cffc460, 0xc013532c60, 0xc01460d7a0)
Mar 26 03:29:36 localhost doh-client[78140]:         /build/dns-over-https/src/go/pkg/mod/github.com/miekg/dns@v1.1.27/server.go:37 +0x46
Mar 26 03:29:36 localhost doh-client[78140]: github.com/miekg/dns.(*Server).serveDNS(0xc000119d40, 0xc000ccd000, 0x45, 0x1000, 0xc013532c60)
Mar 26 03:29:36 localhost doh-client[78140]:         /build/dns-over-https/src/go/pkg/mod/github.com/miekg/dns@v1.1.27/server.go:609 +0x2e2
Mar 26 03:29:36 localhost doh-client[78140]: github.com/miekg/dns.(*Server).serveUDPPacket(0xc000119d40, 0xc00028e040, 0xc000ccd000, 0x45, 0x1000, 0xc00029c000, 0xc021188f00)
Mar 26 03:29:36 localhost doh-client[78140]:         /build/dns-over-https/src/go/pkg/mod/github.com/miekg/dns@v1.1.27/server.go:549 +0xb4
Mar 26 03:29:36 localhost doh-client[78140]: created by github.com/miekg/dns.(*Server).serveUDP
Mar 26 03:29:36 localhost doh-client[78140]:         /build/dns-over-https/src/go/pkg/mod/github.com/miekg/dns@v1.1.27/server.go:479 +0x28c
Mar 26 03:29:36 localhost systemd[1]: doh-client.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 26 03:29:36 localhost systemd[1]: doh-client.service: Failed with result 'exit-code'.
Mar 26 03:29:39 localhost systemd[1]: doh-client.service: Scheduled restart job, restart counter is at 2.
Mar 26 03:29:39 localhost systemd[1]: Stopped DNS-over-HTTPS Client.
Mar 26 03:29:39 localhost systemd[1]: Started DNS-over-HTTPS Client.
Mar 26 03:30:42 localhost doh-client[155656]: 2020/03/26 03:30:42 Get "https://dns.dns-over-https.com/dns-query?ct=application/dns-message&dns=AAABEAABAAAAAAABCXNlcnZlYmVlcgNjb20AAC8AAQAAKQIAAACAAAAcAAoAGESi31nxW87Y0wD45157q4kpiH4F_0KoRw": read tcp 192.168.0.102:48584->104.24.123.53:443: read: connection reset by peer
Mar 26 03:30:42 localhost doh-client[155656]: 2020/03/26 03:30:42 Get "https://dns.dns-over-https.com/dns-query?ct=application/dns-message&dns=AAABEAABAAAAAAABBGFsNGEDY29tAAAvAAEAACkCAAAAgAAAHAAKABhEot9Z8VvO2NMA-Odee6uJKYh-Bf9CqEc": read tcp 192.168.0.102:48584->104.24.123.53:443: read: connection reset by peer
……
```

# Reproduction process

- Install [scapy](http://www.secdev.org/projects/scapy/).

- Download [reproduce-script.zip](https://github.com/m13253/dns-over-https/files/4386456/reproduce-script.zip).

- Start ``doh-client`` and ``doh-server``.

Note: The domain name `` doh.bgme.me`` in the `` doh-client2server.conf`` file has been resolved locally and the corresponding `` nginx`` has been set. Please modify it during testing.

```
./doh-client -conf ./doh-client2server.conf &> /dev/null &
./doh-server -conf ./doh-server.conf  &> /dev/null &
```

-  Use `` top`` to view ``doh-client``, ``doh-server`` resource usage.

```
top -p $(ps -ef | grep doh-server | sed 2d | awk '{print $2}') -p $(ps -ef | grep doh-client | sed 2d | awk '{print $2}')
```

- Use the `` send_nsec_dns_pkgs.py`` script for testing

Uncomment the corresponding line in the last part of `` send_nsec_dns_pkgs.py`` according to the required frequency of sending packets, and then run the script to send the packets.

```
sudo python send_nsec_dns_pkgs.py
```

Set ``inter`` to ``0.1``, ``0.01`` , `` 0.001``, and ``0``, and the result is as follows:
![send_nsec_pkgs](https://user-images.githubusercontent.com/22741471/77634541-17958180-6f8c-11ea-84bc-66858c7ac528.png)

As the packet sending frequency increases, the memory usage of `` doh-client`` also increases.
When the test was over, the memory usage of `` doh-client`` dropped extremely slowly and still maintained a high memory usage.

Use wireshark to compare the packet sending frequency bewteen BIND and test script.
It can seen that the actual packet sending frequency of BIND is much higher than our test scipt (set inter to 0).

Test script
![send_scipt_dns](https://user-images.githubusercontent.com/22741471/77634585-2b40e800-6f8c-11ea-93d9-2faf809ab905.png)

BIND
![dns_nsec_full](https://user-images.githubusercontent.com/22741471/77634623-3bf15e00-6f8c-11ea-99be-a93b2fd37655.png)
![dns_nsec_full_12940](https://user-images.githubusercontent.com/22741471/77634631-3eec4e80-6f8c-11ea-87e6-8b67ccdb4037.png)

**Comment by m13253** [comment]
Thank you for your detailed and pretty-formatted issue report with reproduce steps!

This is a serious bug, and I currently have no idea why it happens (because the stack trace points to the HTTP standard library).
I'm trying to investigate it.

**Comment by Jamesits** [comment]
Related: https://github.com/golang/go/issues/37494

**Comment by AZ-X** [comment]
@yingziwu Could you try this : https://github.com/topics/dnscrypt-proxy-r2
You have to build it by yourself.

**Comment by buckaroogeek** [comment]
@yingziwu - @Jamesits suggests that https://github.com/golang/go/issues/37494 might be related to the memory leak. As noted in the golan thread, that issue has been resolved. Do you by chance still see the memory leak after ensuring that current go libraries and current go release are used? Wondering if this issue can be closed and doh-client users do not need to worry?

thanks

**Comment by m13253** [comment]
I believe this problem should be fixed by the Go standard library.
Closing due to inactivity, please let me know if the problem persists.
